/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.fcse.cachesim.gui.construction;

import edu.fcse.cachesim.gui.utils.StringLiterals;
import edu.fcse.cachesim.gui.utils.WrapLayout;
import edu.fcse.cachesim.implementation.CPUCoreImpl;
import edu.fcse.cachesim.implementation.CacheLevelImpl;
import edu.fcse.cachesim.interfaces.CPUCore;
import edu.fcse.cachesim.interfaces.CacheLevel;
import edu.fcse.cachesim.interfaces.ReplacementPolicy;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.HashMap;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Atanasovski
 */
public class ConstructionJFrame2 extends javax.swing.JFrame {

    Map<String, CacheLevelGUIRepresentation> createdElements;
    Map<String, CPUCoreGUIRepresentation> createdCPUs;
    DropCpuElementLabel dropL1, dropL2, dropL3;
    private String selectedCPUCore;

    private DrawArchitecturePanel drawPanel;

    /**
     * Creates new form ConstructionJFrame2
     */
    public ConstructionJFrame2() {
        createdElements = new HashMap<>();
        createdCPUs = new HashMap<>();

        initComponents();
        createdElementsPanel.setLayout(new WrapLayout(WrapLayout.LEFT, 5, 5));
        createdElementsPanelAssemble.setLayout(new WrapLayout(WrapLayout.CENTER, 5, 5));
        createdCPUsPanel.setLayout(new WrapLayout(WrapLayout.CENTER, 5, 5));
        dropPanel.setLayout(new WrapLayout(WrapLayout.CENTER, 5, 5));
        dropL1 = new DropCpuElementLabel("Drop L1 cache element here", 1);
        dropL2 = new DropCpuElementLabel("Drop L2 cache element here", 2);
        dropL3 = new DropCpuElementLabel("Drop L3 cache element here", 3);
        java.awt.Font dropFont = new java.awt.Font("Tahoma", 2, 11);
        dropL1.setFont(dropFont);
        dropL2.setFont(dropFont);
        dropL3.setFont(dropFont);

        dropL1.setHorizontalAlignment(SwingConstants.CENTER);
        dropL2.setHorizontalAlignment(SwingConstants.CENTER);
        dropL3.setHorizontalAlignment(SwingConstants.CENTER);

        dropL1.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY));
        dropL2.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY));
        dropL3.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY));

        dropL1.setPreferredSize(new Dimension((int) dropPanel.getSize().getWidth(), 55));
        dropL2.setPreferredSize(new Dimension((int) dropPanel.getSize().getWidth(), 55));
        dropL3.setPreferredSize(new Dimension((int) dropPanel.getSize().getWidth(), 55));

        dropPanel.add(dropL1);
        dropPanel.add(dropL2);
        dropPanel.add(dropL3);

        Map<String, CPUCore> kure = new HashMap<>();
        kure.put("Tag", new CPUCoreImpl("Tag", null, null, null));
        kure.put("Tag 1", new CPUCoreImpl("Tag 1", null, null, null));
        drawPanel = new DrawArchitecturePanel(kure);
        drawPanel.setPreferredSize(previewAssemblyPlanel.getSize());
        drawPanel.setSize(previewAssemblyPlanel.getSize());
        previewAssemblyPlanel.add(drawPanel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        constructionTabbedPane = new javax.swing.JTabbedPane();
        elementTabPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelConstruction_CreateNewLevel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonConstruction_RP_LRU = new javax.swing.JRadioButton();
        jRadioButtonConstruction_RP_FIFO = new javax.swing.JRadioButton();
        jRadioButtonConstructuion_RP_BPLRU = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxConstruction_SizeRange = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButtonConstruction_CreateLevel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelToolTipAssoc = new javax.swing.JLabel();
        jLabelToolTipSize = new javax.swing.JLabel();
        jLabelToolTipLW = new javax.swing.JLabel();
        jLabelToolTipUID = new javax.swing.JLabel();
        jLabelToolTipRP = new javax.swing.JLabel();
        jTextFieldAssoc = new javax.swing.JTextField();
        jTextFieldSize = new javax.swing.JTextField();
        jTextFieldLineW = new javax.swing.JTextField();
        jTextFieldUID = new javax.swing.JTextField();
        createdElementsScrollPane = new javax.swing.JScrollPane();
        createdElementsPanel = new javax.swing.JPanel();
        jButtonDeleteSelected = new javax.swing.JButton();
        jLabelSelected = new javax.swing.JLabel();
        assemblyTabPanel = new javax.swing.JPanel();
        combineElementsPanel = new javax.swing.JPanel();
        createdElementsScrollAssemble = new javax.swing.JScrollPane();
        createdElementsPanelAssemble = new javax.swing.JPanel();
        createdCPUsScroll = new javax.swing.JScrollPane();
        createdCPUsPanel = new javax.swing.JPanel();
        jPanelSelectedCPU = new javax.swing.JPanel();
        jButtonCreateCore = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        dropPanel = new javax.swing.JPanel();
        jButtonDeleteCore = new javax.swing.JButton();
        previewAssemblyPlanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        constructionTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                constructionTabbedPaneStateChanged(evt);
            }
        });

        jLabel1.setText("<html>Create the separate cache levelts and save them. <br/>Then go to the \"Assemble Cache Elements\" tab to combine them into CPUs</html>");

        jPanelConstruction_CreateNewLevel.setBorder(javax.swing.BorderFactory.createTitledBorder("Create New Cache Element"));

        jLabel2.setText("Choose replacement policy:");

        jRadioButtonConstruction_RP_LRU.setSelected(true);
        jRadioButtonConstruction_RP_LRU.setText("LRU");
        jRadioButtonConstruction_RP_LRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonConstruction_RP_LRUActionPerformed(evt);
            }
        });

        jRadioButtonConstruction_RP_FIFO.setText("FIFO");

        jRadioButtonConstructuion_RP_BPLRU.setText("Bit PLRU");

        jLabel3.setText("Associativity:");

        jLabel4.setText("Size:");

        jComboBoxConstruction_SizeRange.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "B", "KB", "MB" }));

        jLabel5.setText("UID:");

        jButtonConstruction_CreateLevel.setText("Create Level");
        jButtonConstruction_CreateLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConstruction_CreateLevelActionPerformed(evt);
            }
        });

        jLabel10.setText("Line width:");

        jLabel11.setText("B");

        jLabelToolTipAssoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/fcse/cachesim/gui/construction/warning.png"))); // NOI18N

        jLabelToolTipSize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/fcse/cachesim/gui/construction/warning.png"))); // NOI18N

        jLabelToolTipLW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/fcse/cachesim/gui/construction/warning.png"))); // NOI18N

        jLabelToolTipUID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/fcse/cachesim/gui/construction/warning.png"))); // NOI18N

        jLabelToolTipRP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/fcse/cachesim/gui/construction/warning.png"))); // NOI18N
        jLabelToolTipRP.setToolTipText("");

        javax.swing.GroupLayout jPanelConstruction_CreateNewLevelLayout = new javax.swing.GroupLayout(jPanelConstruction_CreateNewLevel);
        jPanelConstruction_CreateNewLevel.setLayout(jPanelConstruction_CreateNewLevelLayout);
        jPanelConstruction_CreateNewLevelLayout.setHorizontalGroup(
            jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelToolTipRP))
                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                        .addComponent(jRadioButtonConstruction_RP_LRU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonConstruction_RP_FIFO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonConstructuion_RP_BPLRU))
                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonConstruction_CreateLevel)
                        .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                            .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                                    .addComponent(jLabelToolTipLW)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel10))
                                .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                                    .addComponent(jLabelToolTipUID)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5))
                                .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelToolTipSize)
                                        .addComponent(jLabelToolTipAssoc))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldAssoc)
                                .addComponent(jTextFieldSize)
                                .addComponent(jTextFieldLineW)
                                .addComponent(jTextFieldUID, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxConstruction_SizeRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))))))
        );
        jPanelConstruction_CreateNewLevelLayout.setVerticalGroup(
            jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelToolTipRP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonConstruction_RP_LRU)
                    .addComponent(jRadioButtonConstruction_RP_FIFO)
                    .addComponent(jRadioButtonConstructuion_RP_BPLRU))
                .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelToolTipAssoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelToolTipSize))
                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldAssoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                                .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxConstruction_SizeRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelToolTipLW)
                                            .addComponent(jLabel10)))
                                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldLineW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel11))
                        .addGap(8, 8, 8)
                        .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabelToolTipUID)
                            .addComponent(jTextFieldUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jButtonConstruction_CreateLevel)))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        createdElementsScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Created Cache Elements"));
        createdElementsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        createdElementsPanel.setLayout(null);
        createdElementsScrollPane.setViewportView(createdElementsPanel);

        jButtonDeleteSelected.setText("Delete Selected");
        jButtonDeleteSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSelectedActionPerformed(evt);
            }
        });

        jLabelSelected.setText("Selected:");

        javax.swing.GroupLayout elementTabPanelLayout = new javax.swing.GroupLayout(elementTabPanel);
        elementTabPanel.setLayout(elementTabPanelLayout);
        elementTabPanelLayout.setHorizontalGroup(
            elementTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elementTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(elementTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, elementTabPanelLayout.createSequentialGroup()
                        .addComponent(jPanelConstruction_CreateNewLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(elementTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(elementTabPanelLayout.createSequentialGroup()
                                .addComponent(jLabelSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDeleteSelected))
                            .addComponent(createdElementsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        elementTabPanelLayout.setVerticalGroup(
            elementTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elementTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(elementTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelConstruction_CreateNewLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(elementTabPanelLayout.createSequentialGroup()
                        .addComponent(createdElementsScrollPane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(elementTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDeleteSelected)
                            .addComponent(jLabelSelected))))
                .addContainerGap())
        );

        constructionTabbedPane.addTab("Create Cache Elements", elementTabPanel);

        combineElementsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Create"));

        createdElementsScrollAssemble.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        createdElementsPanelAssemble.setBorder(javax.swing.BorderFactory.createTitledBorder("Created Elements"));
        createdElementsPanelAssemble.setPreferredSize(new java.awt.Dimension(122, 244));

        javax.swing.GroupLayout createdElementsPanelAssembleLayout = new javax.swing.GroupLayout(createdElementsPanelAssemble);
        createdElementsPanelAssemble.setLayout(createdElementsPanelAssembleLayout);
        createdElementsPanelAssembleLayout.setHorizontalGroup(
            createdElementsPanelAssembleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );
        createdElementsPanelAssembleLayout.setVerticalGroup(
            createdElementsPanelAssembleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );

        createdElementsScrollAssemble.setViewportView(createdElementsPanelAssemble);

        createdCPUsScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        createdCPUsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Created Cores"));
        createdCPUsPanel.setPreferredSize(new java.awt.Dimension(95, 190));

        javax.swing.GroupLayout createdCPUsPanelLayout = new javax.swing.GroupLayout(createdCPUsPanel);
        createdCPUsPanel.setLayout(createdCPUsPanelLayout);
        createdCPUsPanelLayout.setHorizontalGroup(
            createdCPUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        createdCPUsPanelLayout.setVerticalGroup(
            createdCPUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        createdCPUsScroll.setViewportView(createdCPUsPanel);

        jPanelSelectedCPU.setBorder(javax.swing.BorderFactory.createTitledBorder("Create Core"));
        jPanelSelectedCPU.setPreferredSize(new java.awt.Dimension(354, 246));

        jButtonCreateCore.setText("Create");
        jButtonCreateCore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateCoreActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(102, 255, 0));
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("<-Drag from the created elements");

        dropPanel.setPreferredSize(new java.awt.Dimension(320, 194));

        javax.swing.GroupLayout dropPanelLayout = new javax.swing.GroupLayout(dropPanel);
        dropPanel.setLayout(dropPanelLayout);
        dropPanelLayout.setHorizontalGroup(
            dropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        dropPanelLayout.setVerticalGroup(
            dropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelSelectedCPULayout = new javax.swing.GroupLayout(jPanelSelectedCPU);
        jPanelSelectedCPU.setLayout(jPanelSelectedCPULayout);
        jPanelSelectedCPULayout.setHorizontalGroup(
            jPanelSelectedCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectedCPULayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSelectedCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSelectedCPULayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCreateCore)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelSelectedCPULayout.createSequentialGroup()
                        .addComponent(dropPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelSelectedCPULayout.setVerticalGroup(
            jPanelSelectedCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSelectedCPULayout.createSequentialGroup()
                .addComponent(dropPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSelectedCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreateCore)
                    .addComponent(jLabel6)))
        );

        jButtonDeleteCore.setText("Delete Core");
        jButtonDeleteCore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout combineElementsPanelLayout = new javax.swing.GroupLayout(combineElementsPanel);
        combineElementsPanel.setLayout(combineElementsPanelLayout);
        combineElementsPanelLayout.setHorizontalGroup(
            combineElementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(combineElementsPanelLayout.createSequentialGroup()
                .addComponent(createdElementsScrollAssemble, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSelectedCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(combineElementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createdCPUsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jButtonDeleteCore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        combineElementsPanelLayout.setVerticalGroup(
            combineElementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createdElementsScrollAssemble, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(combineElementsPanelLayout.createSequentialGroup()
                .addGroup(combineElementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSelectedCPU, 242, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(combineElementsPanelLayout.createSequentialGroup()
                        .addComponent(createdCPUsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteCore)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        previewAssemblyPlanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                previewAssemblyPlanelComponentResized(evt);
            }
        });

        javax.swing.GroupLayout previewAssemblyPlanelLayout = new javax.swing.GroupLayout(previewAssemblyPlanel);
        previewAssemblyPlanel.setLayout(previewAssemblyPlanelLayout);
        previewAssemblyPlanelLayout.setHorizontalGroup(
            previewAssemblyPlanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        previewAssemblyPlanelLayout.setVerticalGroup(
            previewAssemblyPlanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout assemblyTabPanelLayout = new javax.swing.GroupLayout(assemblyTabPanel);
        assemblyTabPanel.setLayout(assemblyTabPanelLayout);
        assemblyTabPanelLayout.setHorizontalGroup(
            assemblyTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(combineElementsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(previewAssemblyPlanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(assemblyTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        assemblyTabPanelLayout.setVerticalGroup(
            assemblyTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assemblyTabPanelLayout.createSequentialGroup()
                .addComponent(combineElementsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previewAssemblyPlanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        constructionTabbedPane.addTab("Assemble Cache Elements", assemblyTabPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(constructionTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(constructionTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonConstruction_RP_LRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonConstruction_RP_LRUActionPerformed

    }//GEN-LAST:event_jRadioButtonConstruction_RP_LRUActionPerformed

    private void jButtonConstruction_CreateLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConstruction_CreateLevelActionPerformed
        String tag = jTextFieldUID.getText();
        if (tag.length() == 0) {
            JOptionPane.showMessageDialog(null, "UID tag required for level\n", "EDUCacheSim: " + "Create configuration", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int result = JOptionPane.YES_OPTION;
        if (createdElements.containsKey(tag)) {
            result = JOptionPane.showConfirmDialog(null, "Specified UID exists, replace?", "EDUCacheSim: Create configuration", JOptionPane.YES_NO_OPTION);
        }
        if (result == JOptionPane.NO_OPTION) {
            return;
        }
        ReplacementPolicy rp = getReplacementPolicyChosen();
        try {
            int assoc = Integer.parseInt(jTextFieldAssoc.getText());
            int size = Integer.parseInt(jTextFieldSize.getText());
            int linew = Integer.parseInt(jTextFieldLineW.getText());
            String sizeRange = (String) jComboBoxConstruction_SizeRange.getSelectedItem();
            switch (sizeRange) {
                case "KB":
                    size *= 1024;
                    break;
                case "MB":
                    size *= 1024 * 1024;
                    break;
            }
            if (size < assoc * linew) {
                JOptionPane.showMessageDialog(null, "Cache Size must be at least (LineWidth*Associativity) Bytes\n", "EDUCacheSim: " + "Create configuration", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            CacheLevel cl = new CacheLevelImpl(tag, rp, size, assoc, linew);
            createdElements.put(tag, new CacheLevelGUIRepresentation(this, cl));

            createdElementsPanel.add(new CacheLevelGUIRepresentation(this, cl));
            createdElementsPanel.invalidate();
            createdElementsPanel.updateUI();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Numbers only required in fields Associativity, Size and Line width\n", "EDUCacheSim: " + "Create configuration", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonConstruction_CreateLevelActionPerformed

    private void jButtonDeleteSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSelectedActionPerformed
        if (selectedCacheElement != null && createdElements.containsKey(selectedCacheElement)) {
            for (String coreTag : createdCPUs.keySet()) {
                CPUCoreGUIRepresentation cc = createdCPUs.get(coreTag);
                if (cc.getCore().getLevel(selectedCacheElement) != null) {
                    JOptionPane.showMessageDialog(null, "Cache level you are trying to delete is being used in the CPUCore with the tag: " + coreTag + ". Delete the cpu core first", "EDUCacheSim: " + "Delete cache level", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            }
            createdElements.remove(selectedCacheElement);
            createdElementsPanel.removeAll();
            for (String tag : createdElements.keySet()) {
                createdElementsPanel.add(createdElements.get(tag));
            }
            selectedCacheElement = null;
            createdElementsPanel.updateUI();
            jLabelSelected.setText("Selected: none");
        }
    }//GEN-LAST:event_jButtonDeleteSelectedActionPerformed

    private void constructionTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_constructionTabbedPaneStateChanged

        JPanel containingPanel = null;
        if (constructionTabbedPane.getSelectedIndex() == 0) {
            createdElementsPanel.removeAll();
            containingPanel = createdElementsPanel;
        } else if (constructionTabbedPane.getSelectedIndex() == 1) {
            createdElementsPanelAssemble.removeAll();
            containingPanel = createdElementsPanelAssemble;
        }
        if (containingPanel != null) {
            for (String key : createdElements.keySet()) {
                containingPanel.add(createdElements.get(key));
            }
            containingPanel.updateUI();
        }
    }//GEN-LAST:event_constructionTabbedPaneStateChanged

    private void jButtonCreateCoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateCoreActionPerformed
        if (dropL1.hasLevel() && dropL2.hasLevel() && dropL3.hasLevel()) {
            String s = JOptionPane.showInputDialog("Enter a UID for the new CPU core:");
            CPUCore newCore = new CPUCoreImpl(s, dropL1.getAssociatedLevel(), dropL2.getAssociatedLevel(), dropL3.getAssociatedLevel());
            createdCPUs.put(s, new CPUCoreGUIRepresentation(this, newCore));
            createdCPUsPanel.add(createdCPUs.get(s));
            createdCPUsPanel.updateUI();
            updateDrawing();
        } else {
            JOptionPane.showMessageDialog(null, "You need to add a cache element for all the levels\n", "EDUCacheSim: " + "Create CPU Core", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCreateCoreActionPerformed

    private void jButtonDeleteCoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCoreActionPerformed
        if (selectedCPUCore != null && createdCPUs.containsKey(selectedCPUCore)) {
            createdCPUs.remove(selectedCPUCore);
            createdCPUsPanel.removeAll();
            for (String tag : createdCPUs.keySet()) {
                createdCPUsPanel.add(createdCPUs.get(tag));
            }
            createdCPUsPanel.updateUI();
            selectedCPUCore = null;
        }
    }//GEN-LAST:event_jButtonDeleteCoreActionPerformed

    private void previewAssemblyPlanelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_previewAssemblyPlanelComponentResized
        int heightDif = Math.abs(previewAssemblyPlanel.getHeight() - drawPanel.getHeight());
        int widthDif = Math.abs(previewAssemblyPlanel.getWidth() - drawPanel.getWidth());
        if (heightDif > 30 || widthDif > 50) {
            drawPanel.setSize(previewAssemblyPlanel.getSize());
            drawPanel.updateUI();
        }
    }//GEN-LAST:event_previewAssemblyPlanelComponentResized
    private ReplacementPolicy getReplacementPolicyChosen() {
        if (jRadioButtonConstruction_RP_FIFO.isSelected()) {
            return ReplacementPolicy.FIFO;
        } else if (jRadioButtonConstruction_RP_LRU.isSelected()) {
            return ReplacementPolicy.LRU;
        }
        return ReplacementPolicy.BitPLRU;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConstructionJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConstructionJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConstructionJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConstructionJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConstructionJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel assemblyTabPanel;
    private javax.swing.JPanel combineElementsPanel;
    private javax.swing.JTabbedPane constructionTabbedPane;
    private javax.swing.JPanel createdCPUsPanel;
    private javax.swing.JScrollPane createdCPUsScroll;
    private javax.swing.JPanel createdElementsPanel;
    private javax.swing.JPanel createdElementsPanelAssemble;
    private javax.swing.JScrollPane createdElementsScrollAssemble;
    private javax.swing.JScrollPane createdElementsScrollPane;
    private javax.swing.JPanel dropPanel;
    private javax.swing.JPanel elementTabPanel;
    private javax.swing.JButton jButtonConstruction_CreateLevel;
    private javax.swing.JButton jButtonCreateCore;
    private javax.swing.JButton jButtonDeleteCore;
    private javax.swing.JButton jButtonDeleteSelected;
    private javax.swing.JComboBox jComboBoxConstruction_SizeRange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelSelected;
    private javax.swing.JLabel jLabelToolTipAssoc;
    private javax.swing.JLabel jLabelToolTipLW;
    private javax.swing.JLabel jLabelToolTipRP;
    private javax.swing.JLabel jLabelToolTipSize;
    private javax.swing.JLabel jLabelToolTipUID;
    private javax.swing.JPanel jPanelConstruction_CreateNewLevel;
    private javax.swing.JPanel jPanelSelectedCPU;
    private javax.swing.JRadioButton jRadioButtonConstruction_RP_FIFO;
    private javax.swing.JRadioButton jRadioButtonConstruction_RP_LRU;
    private javax.swing.JRadioButton jRadioButtonConstructuion_RP_BPLRU;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldAssoc;
    private javax.swing.JTextField jTextFieldLineW;
    private javax.swing.JTextField jTextFieldSize;
    private javax.swing.JTextField jTextFieldUID;
    private javax.swing.JPanel previewAssemblyPlanel;
    // End of variables declaration//GEN-END:variables

    void showInfo(String tag) {
        if (createdElements.containsKey(tag)) {
            CacheLevelGUIRepresentation selected = createdElements.get(tag);
            CacheLevel level = selected.getCacheLevel();
            jTextFieldAssoc.setText(level.getAssoc() + "");
            jTextFieldLineW.setText(level.getLineWidth() + "");
            jTextFieldSize.setText(level.getSize() + "");
            jTextFieldUID.setText(tag);
            jLabelSelected.setText("<html>Selected <b>" + tag + "</b></html>");
            selectedCacheElement = tag;
        }
    }
    private String selectedCacheElement;

    void loadCoreInfo(CPUCore core) {
        selectedCPUCore = core.getTag();
    }

    public Map<String, CPUCoreGUIRepresentation> getCreatedCPUs() {
        return createdCPUs;
    }

    public JPanel getCreatedCPUsPanel() {
        return createdCPUsPanel;
    }

    private void updateDrawing() {
        Map<String, CPUCore> cores = new HashMap<>();
        for (String tag : createdCPUs.keySet()) {
            cores.put(tag, createdCPUs.get(tag).getCore());
        }
        drawPanel.setCores(cores);
        drawPanel.updateUI();
    }
}
