package edu.fcse.cachesim.gui.construction;

import edu.fcse.cachesim.filemanip.CCFCreator;
import edu.fcse.cachesim.gui.simulation.SimulationJFrame;
import edu.fcse.cachesim.gui.utils.CCFileFilter;
import edu.fcse.cachesim.gui.utils.StringLiterals;
import edu.fcse.cachesim.gui.utils.TooltipHints;
import edu.fcse.cachesim.implementation.ArchitectureImpl;
import edu.fcse.cachesim.implementation.CPUCoreImpl;
import edu.fcse.cachesim.implementation.CacheLevelImpl;
import edu.fcse.cachesim.interfaces.Architecture;
import edu.fcse.cachesim.interfaces.CPUCore;
import edu.fcse.cachesim.interfaces.CacheLevel;
import edu.fcse.cachesim.interfaces.Referable;
import edu.fcse.cachesim.interfaces.ReplacementPolicy;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * Construction mode for the simulator, contains the components for creating
 * CacheLevels and combining them into CPUCores, the created elements can be
 * saved in .ccf files (Cache Configuration File).
 *
 * @author Blagoj Atanasovski;
 *
 */
public class ConstructionJFrame extends javax.swing.JFrame {

    /*
     * Parent frame that displays this one
     */
    private SimulationJFrame simulationFrame;
    /*
     * Frame that shows the full tool tip texts
     */
    private InfoJFrame infoFrame;
    /*
     * Collection of all the created elements, CacheLevels and CPUCores
     */
    private Map<String, Referable> createdElements;

    /**
     * Creates new form ConstructionJFrame
     *
     * @param simulationFr The Parent Simulation Frame that created this
     * construction frame
     */
    public ConstructionJFrame(SimulationJFrame simulationFr) {
        initComponents();
        createdElements = new HashMap<>();
        simulationFrame = simulationFr;
        jTable1.getSelectionModel().addListSelectionListener(new TableSelectionListener(this, jTable1));
        initToolTips();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupConstruction_RP = new javax.swing.ButtonGroup();
        jPanelConstruction = new javax.swing.JPanel();
        jPanelConstruction_CreationOption = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPaneConstruction_CreateNew = new javax.swing.JTabbedPane();
        jPanelConstruction_CreateNewLevel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonConstruction_RP_LRU = new javax.swing.JRadioButton();
        jRadioButtonConstruction_RP_FIFO = new javax.swing.JRadioButton();
        jRadioButtonConstructuion_RP_BPLRU = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxConstruction_SizeRange = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButtonConstruction_CreateLevel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelToolTipAssoc = new javax.swing.JLabel();
        jLabelToolTipSize = new javax.swing.JLabel();
        jLabelToolTipLW = new javax.swing.JLabel();
        jLabelToolTipUID = new javax.swing.JLabel();
        jLabelToolTipRP = new javax.swing.JLabel();
        jTextFieldAssoc = new javax.swing.JTextField();
        jTextFieldSize = new javax.swing.JTextField();
        jTextFieldLineW = new javax.swing.JTextField();
        jTextFieldUID = new javax.swing.JTextField();
        jPanelConstruction_CreateNewCore = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxConstruction_CoreL1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxConstruction_CoreL2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxConstruction_CoreL3 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jButtonConstruction_CreateCore = new javax.swing.JButton();
        jTextFieldCoreUID = new javax.swing.JTextField();
        jLabelToolTipCores = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jButton_DeleteFromTable = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuConstruction_Options = new javax.swing.JMenu();
        jMenuItem_SaveConfiguration = new javax.swing.JMenuItem();
        jMenuItem_SaveAndLoadConfig = new javax.swing.JMenuItem();
        jMenuItem_Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDUCacheSim: Construction Mode");

        jLabel1.setText("Create new:");

        jLabel2.setText("Choose replacement policy:");

        buttonGroupConstruction_RP.add(jRadioButtonConstruction_RP_LRU);
        jRadioButtonConstruction_RP_LRU.setSelected(true);
        jRadioButtonConstruction_RP_LRU.setText("LRU");
        jRadioButtonConstruction_RP_LRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonConstruction_RP_LRUActionPerformed(evt);
            }
        });

        buttonGroupConstruction_RP.add(jRadioButtonConstruction_RP_FIFO);
        jRadioButtonConstruction_RP_FIFO.setText("FIFO");

        buttonGroupConstruction_RP.add(jRadioButtonConstructuion_RP_BPLRU);
        jRadioButtonConstructuion_RP_BPLRU.setText("Bit PLRU");

        jLabel3.setText("Associativity:");

        jLabel4.setText("Size:");

        jComboBoxConstruction_SizeRange.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "B", "KB", "MB" }));

        jLabel5.setText("UID:");

        jButtonConstruction_CreateLevel.setText("Create Level");
        jButtonConstruction_CreateLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConstruction_CreateLevelActionPerformed(evt);
            }
        });

        jLabel10.setText("Line width:");

        jLabel11.setText("B");

        jLabelToolTipAssoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/fcse/cachesim/gui/construction/warning.png"))); // NOI18N

        jLabelToolTipSize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/fcse/cachesim/gui/construction/warning.png"))); // NOI18N

        jLabelToolTipLW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/fcse/cachesim/gui/construction/warning.png"))); // NOI18N

        jLabelToolTipUID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/fcse/cachesim/gui/construction/warning.png"))); // NOI18N

        jLabelToolTipRP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/fcse/cachesim/gui/construction/warning.png"))); // NOI18N
        jLabelToolTipRP.setToolTipText("");

        javax.swing.GroupLayout jPanelConstruction_CreateNewLevelLayout = new javax.swing.GroupLayout(jPanelConstruction_CreateNewLevel);
        jPanelConstruction_CreateNewLevel.setLayout(jPanelConstruction_CreateNewLevelLayout);
        jPanelConstruction_CreateNewLevelLayout.setHorizontalGroup(
            jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelToolTipRP))
                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                        .addComponent(jRadioButtonConstruction_RP_LRU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonConstruction_RP_FIFO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonConstructuion_RP_BPLRU))
                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonConstruction_CreateLevel)
                        .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                            .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                                    .addComponent(jLabelToolTipLW)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel10))
                                .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                                    .addComponent(jLabelToolTipUID)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5))
                                .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelToolTipSize)
                                        .addComponent(jLabelToolTipAssoc))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldAssoc)
                                .addComponent(jTextFieldSize)
                                .addComponent(jTextFieldLineW)
                                .addComponent(jTextFieldUID, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxConstruction_SizeRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelConstruction_CreateNewLevelLayout.setVerticalGroup(
            jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelToolTipRP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonConstruction_RP_LRU)
                    .addComponent(jRadioButtonConstruction_RP_FIFO)
                    .addComponent(jRadioButtonConstructuion_RP_BPLRU))
                .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelToolTipAssoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelToolTipSize))
                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldAssoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                                .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxConstruction_SizeRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelToolTipLW)
                                            .addComponent(jLabel10)))
                                    .addGroup(jPanelConstruction_CreateNewLevelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldLineW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel11))
                        .addGap(8, 8, 8)
                        .addGroup(jPanelConstruction_CreateNewLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabelToolTipUID)
                            .addComponent(jTextFieldUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jButtonConstruction_CreateLevel)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPaneConstruction_CreateNew.addTab("Cache Level", jPanelConstruction_CreateNewLevel);

        jPanelConstruction_CreateNewCore.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelConstruction_CreateNewCoreComponentShown(evt);
            }
        });

        jLabel6.setText("L1 Cache:");

        jComboBoxConstruction_CoreL1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "C1_L1_FIFO", "C2_L1_FIFO", "C1_L2_LRU", "C2_L2_LRU", "L3_FIFO" }));

        jLabel7.setText("L2 Cache:");

        jComboBoxConstruction_CoreL2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "C1_L1_FIFO", "C2_L1_FIFO", "C1_L2_LRU", "C2_L2_LRU", "L3_FIFO" }));

        jLabel8.setText("L3 Cache:");

        jComboBoxConstruction_CoreL3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "C1_L1_FIFO", "C2_L1_FIFO", "C1_L2_LRU", "C2_L2_LRU", "L3_FIFO" }));

        jLabel9.setText("Core UID:");

        jButtonConstruction_CreateCore.setText("Create Core");
        jButtonConstruction_CreateCore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConstruction_CreateCoreActionPerformed(evt);
            }
        });

        jLabelToolTipCores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/fcse/cachesim/gui/construction/warning.png"))); // NOI18N

        javax.swing.GroupLayout jPanelConstruction_CreateNewCoreLayout = new javax.swing.GroupLayout(jPanelConstruction_CreateNewCore);
        jPanelConstruction_CreateNewCore.setLayout(jPanelConstruction_CreateNewCoreLayout);
        jPanelConstruction_CreateNewCoreLayout.setHorizontalGroup(
            jPanelConstruction_CreateNewCoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConstruction_CreateNewCoreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConstruction_CreateNewCoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelConstruction_CreateNewCoreLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelToolTipCores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConstruction_CreateCore))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelConstruction_CreateNewCoreLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxConstruction_CoreL1, 0, 167, Short.MAX_VALUE))
                    .addGroup(jPanelConstruction_CreateNewCoreLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxConstruction_CoreL2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelConstruction_CreateNewCoreLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxConstruction_CoreL3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelConstruction_CreateNewCoreLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCoreUID)))
                .addGap(35, 35, 35))
        );
        jPanelConstruction_CreateNewCoreLayout.setVerticalGroup(
            jPanelConstruction_CreateNewCoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConstruction_CreateNewCoreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConstruction_CreateNewCoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelConstruction_CreateNewCoreLayout.createSequentialGroup()
                        .addGroup(jPanelConstruction_CreateNewCoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBoxConstruction_CoreL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelConstruction_CreateNewCoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxConstruction_CoreL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelConstruction_CreateNewCoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxConstruction_CoreL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(13, 13, 13)
                        .addComponent(jTextFieldCoreUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConstruction_CreateNewCoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonConstruction_CreateCore)
                    .addComponent(jLabelToolTipCores))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPaneConstruction_CreateNew.addTab("Cache Core", jPanelConstruction_CreateNewCore);

        javax.swing.GroupLayout jPanelConstruction_CreationOptionLayout = new javax.swing.GroupLayout(jPanelConstruction_CreationOption);
        jPanelConstruction_CreationOption.setLayout(jPanelConstruction_CreationOptionLayout);
        jPanelConstruction_CreationOptionLayout.setHorizontalGroup(
            jPanelConstruction_CreationOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConstruction_CreationOptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConstruction_CreationOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPaneConstruction_CreateNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelConstruction_CreationOptionLayout.setVerticalGroup(
            jPanelConstruction_CreationOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConstruction_CreationOptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneConstruction_CreateNew)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UID", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable1);

        jLabel17.setText("Created Cache Elements");

        jButton_DeleteFromTable.setText("Delete Element");
        jButton_DeleteFromTable.setEnabled(false);
        jButton_DeleteFromTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteFromTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConstructionLayout = new javax.swing.GroupLayout(jPanelConstruction);
        jPanelConstruction.setLayout(jPanelConstructionLayout);
        jPanelConstructionLayout.setHorizontalGroup(
            jPanelConstructionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConstructionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelConstruction_CreationOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelConstructionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addGroup(jPanelConstructionLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConstructionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_DeleteFromTable)))
                .addContainerGap())
        );
        jPanelConstructionLayout.setVerticalGroup(
            jPanelConstructionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConstructionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConstructionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelConstruction_CreationOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelConstructionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_DeleteFromTable)
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );

        jMenuConstruction_Options.setText("Options");

        jMenuItem_SaveConfiguration.setText("Save configuration");
        jMenuItem_SaveConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SaveConfigurationActionPerformed(evt);
            }
        });
        jMenuConstruction_Options.add(jMenuItem_SaveConfiguration);

        jMenuItem_SaveAndLoadConfig.setText("Save and load into simulator");
        jMenuItem_SaveAndLoadConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SaveAndLoadConfigActionPerformed(evt);
            }
        });
        jMenuConstruction_Options.add(jMenuItem_SaveAndLoadConfig);

        jMenuItem_Exit.setText("Exit");
        jMenuConstruction_Options.add(jMenuItem_Exit);

        jMenuBar1.add(jMenuConstruction_Options);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelConstruction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelConstruction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonConstruction_RP_LRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonConstruction_RP_LRUActionPerformed
    }//GEN-LAST:event_jRadioButtonConstruction_RP_LRUActionPerformed

    private void jButtonConstruction_CreateLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConstruction_CreateLevelActionPerformed
        String tag = jTextFieldUID.getText();
        if (tag.length() == 0) {
            JOptionPane.showMessageDialog(null, "UID tag required for level\n", "EDUCacheSim: " + "Create configuration", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int result = JOptionPane.YES_OPTION;
        if (createdElements.containsKey(tag)) {
            result = JOptionPane.showConfirmDialog(null, "Specified UID exists, replace?", "EDUCacheSim: Create configuration", JOptionPane.YES_NO_OPTION);
        }
        if (result == JOptionPane.NO_OPTION) {
            return;
        }
        ReplacementPolicy rp = getReplacementPolicyChosen();
        try {
            int assoc = Integer.parseInt(jTextFieldAssoc.getText());
            int size = Integer.parseInt(jTextFieldSize.getText());
            int linew = Integer.parseInt(jTextFieldLineW.getText());
            String sizeRange = (String) jComboBoxConstruction_SizeRange.getSelectedItem();
            switch (sizeRange) {
                case "KB":
                    size *= 1024;
                    break;
                case "MB":
                    size *= 1024 * 1024;
                    break;
            }
            if (size < assoc * linew) {
                JOptionPane.showMessageDialog(null, "Cache Size must be at least (LineWidth*Associativity) Bytes\n", "EDUCacheSim: " + "Create configuration", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            CacheLevel cl = new CacheLevelImpl(tag, rp, size, assoc, linew);
            createdElements.put(tag, cl);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Numbers only required in fields Associativity, Size and Line width\n", "EDUCacheSim: " + "Create configuration", JOptionPane.INFORMATION_MESSAGE);
        }
        refreshTable();
    }//GEN-LAST:event_jButtonConstruction_CreateLevelActionPerformed

    private void jPanelConstruction_CreateNewCoreComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelConstruction_CreateNewCoreComponentShown
        String[] levels = filterLevels();
        jComboBoxConstruction_CoreL1.setModel(new javax.swing.DefaultComboBoxModel(levels));
        jComboBoxConstruction_CoreL2.setModel(new javax.swing.DefaultComboBoxModel(levels));
        jComboBoxConstruction_CoreL3.setModel(new javax.swing.DefaultComboBoxModel(levels));
    }//GEN-LAST:event_jPanelConstruction_CreateNewCoreComponentShown

    private void jButtonConstruction_CreateCoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConstruction_CreateCoreActionPerformed
        String uid = jTextFieldCoreUID.getText();
        if (uid.length() == 0) {
            JOptionPane.showMessageDialog(null, "UID not specified!\n", "EDUCacheSim: " + "Create configuration", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (createdElements.containsKey(uid)) {
            JOptionPane.showMessageDialog(null, "UID allready used by another element!\n", "EDUCacheSim: " + "Create configuration", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String tag1 = (String) jComboBoxConstruction_CoreL1.getSelectedItem();
        String tag2 = (String) jComboBoxConstruction_CoreL2.getSelectedItem();
        String tag3 = (String) jComboBoxConstruction_CoreL3.getSelectedItem();
        if (tag1.equals(tag2) || tag1.equals(tag3) || tag2.equals(tag3)) {
            JOptionPane.showMessageDialog(null, "A Cache Level instance can be chosen only once!\n", "EDUCacheSim: " + "Create configuration", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        CacheLevel cl1 = (CacheLevel) createdElements.get(tag1);
        CacheLevel cl2 = (CacheLevel) createdElements.get(tag2);
        CacheLevel cl3 = (CacheLevel) createdElements.get(tag3);
        CPUCore core = new CPUCoreImpl(uid, cl1, cl2, cl3);
        createdElements.put(uid, core);
        refreshTable();
    }//GEN-LAST:event_jButtonConstruction_CreateCoreActionPerformed

    private void jMenuItem_SaveConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SaveConfigurationActionPerformed
        saveConfiguration();
    }//GEN-LAST:event_jMenuItem_SaveConfigurationActionPerformed

    private void jButton_DeleteFromTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteFromTableActionPerformed
        int selRow = jTable1.getSelectedRow();
        String tag = (String) jTable1.getModel().getValueAt(selRow, 0);
        createdElements.remove(tag);
        refreshTable();
        jButton_DeleteFromTable.setEnabled(false);
    }//GEN-LAST:event_jButton_DeleteFromTableActionPerformed

    private void jMenuItem_SaveAndLoadConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SaveAndLoadConfigActionPerformed
        File f = saveConfiguration();
        if (f != null) {
            this.dispose();
            simulationFrame.loadConfiguration(f);
        }
    }//GEN-LAST:event_jMenuItem_SaveAndLoadConfigActionPerformed
    private File saveConfiguration() {
        //create an empty architecture and add the cores from the created elements shown in jTable1
        Architecture a = new ArchitectureImpl();
        for (Referable r : createdElements.values()) {
            if (r instanceof CPUCore) {
                a.addCore((CPUCore) r);
            }
        }
        if (a.getNumOfCores() > 0) {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileFilter(new CCFileFilter());
            fileChooser.setSelectedFile(new File("configuration.ccf"));
            int returnVal = fileChooser.showSaveDialog(ConstructionJFrame.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                try {
                    CCFCreator.writeConfigurationToFile(a, file);
                    JOptionPane.showMessageDialog(null, StringLiterals.CONFIGURATION_SAVED, "EDUCacheSim: " + "Save configuration", JOptionPane.INFORMATION_MESSAGE);
                    return file;
                } catch (IOException ex) {
                    Logger.getLogger(ConstructionJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, StringLiterals.CONFIGURATION_ERROR_SAVE + "!\n" + ex.getMessage(), "EDUCacheSim: " + "Save configuration", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } else {
            //if no cores were created prompt there is nothing to save
            JOptionPane.showMessageDialog(null, "No CPU cores created!\n", "EDUCacheSim: " + "Save configuration", JOptionPane.INFORMATION_MESSAGE);
        }
        return null;
    }

    private String[] filterLevels() {
        List<String> list = new ArrayList<>();
        for (Referable r : createdElements.values()) {
            if (r instanceof CacheLevel) {
                list.add(r.getTag());
            }
        }
        String[] toReturn = new String[0];
        return list.toArray(toReturn);
    }

    private void refreshTable() {
        jTable1.setModel(new ConstructionTableModel(createdElements));
        jTable1.invalidate();
    }

    private ReplacementPolicy getReplacementPolicyChosen() {
        if (jRadioButtonConstruction_RP_FIFO.isSelected()) {
            return ReplacementPolicy.FIFO;
        } else if (jRadioButtonConstruction_RP_LRU.isSelected()) {
            return ReplacementPolicy.LRU;
        }
        return ReplacementPolicy.BitPLRU;
    }

    private void initToolTips() {
        jLabelToolTipRP.setToolTipText(TooltipHints.ReplacementPolicyHint);
        jLabelToolTipRP.addMouseListener(new StartToolTipFrameMouseListener(infoFrame, "Replacement Policy", TooltipHints.ReplacementPolicyHint, TooltipHints.ReplacementPolicyLink));

        jLabelToolTipLW.setToolTipText(TooltipHints.LineWidthHint);
        jLabelToolTipLW.addMouseListener(new StartToolTipFrameMouseListener(infoFrame, "Line Width", TooltipHints.LineWidthHint, TooltipHints.LineWidthLink));

        jLabelToolTipSize.setToolTipText(TooltipHints.CacheSizeHint);
        jLabelToolTipSize.addMouseListener(new StartToolTipFrameMouseListener(infoFrame, "Cache Size", TooltipHints.CacheSizeHint, TooltipHints.CacheSizeLink));

        jLabelToolTipAssoc.setToolTipText(TooltipHints.AssociativityHint);
        jLabelToolTipAssoc.addMouseListener(new StartToolTipFrameMouseListener(infoFrame, "Associativity", TooltipHints.AssociativityHint, TooltipHints.AssociativityLink));

        jLabelToolTipUID.setToolTipText(TooltipHints.UIDHint);
        jLabelToolTipUID.addMouseListener(new StartToolTipFrameMouseListener(infoFrame, "UID", TooltipHints.UIDHint, null));

        jLabelToolTipCores.setToolTipText(TooltipHints.CoreHint);
        jLabelToolTipCores.addMouseListener(new StartToolTipFrameMouseListener(infoFrame, "Creating Cores", TooltipHints.CoreHint, null));
    }

    public void enableDeleteButton() {
        jButton_DeleteFromTable.setEnabled(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupConstruction_RP;
    private javax.swing.JButton jButtonConstruction_CreateCore;
    private javax.swing.JButton jButtonConstruction_CreateLevel;
    private javax.swing.JButton jButton_DeleteFromTable;
    private javax.swing.JComboBox jComboBoxConstruction_CoreL1;
    private javax.swing.JComboBox jComboBoxConstruction_CoreL2;
    private javax.swing.JComboBox jComboBoxConstruction_CoreL3;
    private javax.swing.JComboBox jComboBoxConstruction_SizeRange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelToolTipAssoc;
    private javax.swing.JLabel jLabelToolTipCores;
    private javax.swing.JLabel jLabelToolTipLW;
    private javax.swing.JLabel jLabelToolTipRP;
    private javax.swing.JLabel jLabelToolTipSize;
    private javax.swing.JLabel jLabelToolTipUID;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConstruction_Options;
    private javax.swing.JMenuItem jMenuItem_Exit;
    private javax.swing.JMenuItem jMenuItem_SaveAndLoadConfig;
    private javax.swing.JMenuItem jMenuItem_SaveConfiguration;
    private javax.swing.JPanel jPanelConstruction;
    private javax.swing.JPanel jPanelConstruction_CreateNewCore;
    private javax.swing.JPanel jPanelConstruction_CreateNewLevel;
    private javax.swing.JPanel jPanelConstruction_CreationOption;
    private javax.swing.JRadioButton jRadioButtonConstruction_RP_FIFO;
    private javax.swing.JRadioButton jRadioButtonConstruction_RP_LRU;
    private javax.swing.JRadioButton jRadioButtonConstructuion_RP_BPLRU;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPaneConstruction_CreateNew;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAssoc;
    private javax.swing.JTextField jTextFieldCoreUID;
    private javax.swing.JTextField jTextFieldLineW;
    private javax.swing.JTextField jTextFieldSize;
    private javax.swing.JTextField jTextFieldUID;
    // End of variables declaration//GEN-END:variables
}
